package:
  name: menpoproject
  version: "2.0"
  
build:
  number: 0
  noarch_python: True

requirements:
  run:
    - python
    - menpo
    - menpo3d
    - menpocli
    - menpodetect
    - menpofit
    - menpowidgets

about:
  home: https://github.com/menpo
  license: BSD
